[scope.tracer.dispatcher.spans]
max_buffer_size = 1000                  # Maximum span items in buffer before a flush

[scope.tracer.dispatcher.events]
max_buffer_size = 1000                  # Maximum event items in buffer before a flush

[scope.tracer.dispatcher]
frequency = 60000                       # Flush frequency in milliseconds
frequency_in_testmode = 1000            # Flush frequency in test mode in milliseconds
concurrency_level = 5                   # Dispatcher concurrency level
close_timeout = 60                     # Close timeout in Seconds.