version: 2
jobs:
  jdk8:
    working_directory: /home/circleci/scope-guava
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Mvn Verify
          command: ./mvnw verify -fae
          no_output_timeout: 1h
      - run:
          name: Save Scope Logs
          command: |
            mkdir -p /tmp/scope_logs
            mv scope*.log /tmp/scope_logs
          when: always
      - store_artifacts:
          path: /tmp/scope_logs
workflows:
  version: 2
  build_all:
    jobs:
      - jdk8