version: 2
jobs:
  jdk8:
    working_directory: /home/circleci/scope-guava
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: build_maven
          command: ./mvnw verify -fae
          no_output_timeout: 1h
workflows:
  version: 2
  build_all:
    jobs:
      - jdk8